ALTER TABLE messages_content ALTER COLUMN lat SET DATA TYPE DECIMAL(10,8);
ALTER TABLE messages_content ALTER COLUMN lon SET DATA TYPE DECIMAL(11,8);
ALTER TABLE users ALTER COLUMN phone_number SET DATA TYPE VARCHAR(255);
